[mypy]
python_version = 3.12
strict = True   # more exigent
mypy_path = app     # search inside app, the carpet
explicit_package_bases = True   # helps to understand imports
warn_unused_configs = True